apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  BACKEND_URL: http://backend-service:80
  AUTH_URL: http://auth-service:3000
  GRAPHQL_URL: http://graphql-service:3001
  SOCKET_URL: http://socket-service:3002