apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer

  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3006 # cualquier puerto
      targetPort: 3006
      nodePort: 30060