apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-deployment
  labels:
    app: socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
    spec:
      containers:
      - name: socket
        image: bloor06/veterinaria-socket:latest
        ports:
        - containerPort: 3002
        env:
        - name: AUTH_API_URL
          valueFrom:
            configMapKeyRef:
              name: socket-config
              key: AUTH_API_URL