apiVersion: v1
kind: Service
metadata:
  name: socket-service
spec:
  type: LoadBalancer

  selector:
    app: socket
  ports:
    - protocol: TCP
      port: 3002 # cualquier puerto
      targetPort: 3002
      nodePort: 30302
