export const routes = {
	home: "/",
	dashboard: "/dashboard",
	login: "/login",
	register: "/register",
	clientes: "/clientes",
	citas: "/citas",
	compras: "/compras",
	mascotas: "/mascotas",
	productos: "/productos",
	vacunas: "/vacunas",
	ventas: "/ventas",
	detalle_compras: "/compras-detalle",
	habitos_mascota: "/habito-mascotas",
	proveedores: "/proveedores",
	tipo_mascota: "/tipo-mascota",
	tipo_producto: "/tipo-producto",
	detalle_ventas: "/ventas-detalle",
	veterinaria: "/veterinaria",
	veterinario: "/veterinario",
	rooms: "/rooms",
};
