apiVersion: v1
kind: Service
metadata:
  name: graphql-service
spec:
  type: LoadBalancer

  selector:
    app: graphql
  ports:
    - protocol: TCP
      port: 3001 # cualquier puerto
      targetPort: 3001
      nodePort: 30301
