apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  DB_CONNECTION_STRING: mongodb://kubernetes:clave@mongo-service:27017/?retryWrites=true&w=majority
  AMQP_URL: 'amqps://vaygsqtq:rh9Vwc7cNEaq5nE4vOxDuDJmVFrirqq6@fish.rmq.cloudamqp.com/vaygsqtq'
