name: Deploy K8S

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up GKE
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1055208873800/locations/global/workloadIdentityPools/github/providers/veterinaria
          project_id: ${{ secrets.GKE_PROJECT }}

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          cluster_name: 'vet-cluster'
          location: 'us-central1'

      - name: List files in kube directory
        run: |
          ls kube/

      - name: Deploy to GKE
        working-directory: ./kube
        run: |
          kubectl apply -f auth-gateway/
          kubectl apply -f backend/
          kubectl apply -f frontend/
          kubectl apply -f auth-microservice/
          kubectl apply -f mongo/
          kubectl apply -f postgresql/
          kubectl apply -f socket/
          kubectl apply -f graphql/

      - name: Get pods status
        run: kubectl get pods
