name: Deploy K8S

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up GKE
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/1055208873800/locations/global/workloadIdentityPools/github/providers/veterinaria

      - name: Configure kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONF }}
          kubectl-version: v1.24.2
      - run: ls

      - name: Deploy to GKE
        working-directory: ./kube
        run: |
          ls
          kubectl apply -f ./auth-gateway -f ./backend -f ./frontend -f ./auth-microservice -f ./mongo -f ./postgresql -f ./socket -f ./graphql
          kubectl get pods
