name: Deploy K8S

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          workload_identity_provider: projects/1055208873800/locations/global/workloadIdentityPools/github/providers/veterinaria

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v2
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}

      - name: List files in kube directory
        run: |
          ls kube/

      - name: Deploy to GKE
        working-directory: ./kube
        run: |
          kubectl apply -f auth-gateway/
          kubectl apply -f backend/
          kubectl apply -f frontend/
          kubectl apply -f auth-microservice/
          kubectl apply -f mongo/
          kubectl apply -f postgresql/
          kubectl apply -f socket/
          kubectl apply -f graphql/

      - name: Get pods status
        run: kubectl get pods
