name: Deploy K8S

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        working-directory: ./k8s

    steps:
      - name: GKE Set Context
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          export_default_credentials: true 

      - name: Deploy to GKE
        run: |
          ls
          pwd
          kubectl apply -f ./auth-gateway -f ./backend -f ./frontend -f ./auth-microservice -f ./mongo -f ./postgresql -f ./socket -f ./graphql
          kubectl get pods