name: Deploy K8S

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up GKE
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/1055208873800/locations/global/workloadIdentityPools/github/providers/veterinaria

      - name: Deploy to GKE
        working-directory: ./kube
        run: |
          kubectl apply -f ./auth-gateway -f ./backend -f ./frontend -f ./auth-microservice -f ./mongo -f ./postgresql -f ./socket -f ./graphql
          kubectl get pods
